version: "3.9"
services:
  database:
    container_name: Libeery-DB
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=Libeery-DB
    ports:
      - "5433:5432"
    volumes:
      - db:/var/lib/postgresql/data 

volumes:
  db:
